### ISSUE TITLE
當老師的名字只有兩個字時，課程名稱的最後一個字會跳到下一行

### ISSUE THREAD

**Issue by green-leek** [MksYi/stustExplorer-NodeJS#1]
在 stustClass.js 裡不應該用 length - 3 的方式獲取老師的名字。

**Comment by MksYi** [comment]
這是一個使用笨方法獲取的方式~
當時也有想到 TeacherName > 3 & TeacherName < 3 的情況
但爬取到的資料範例如下：
導師時間王小明 C303
[課程名稱][老師名稱] [教室位置]

問題在於無從參考「課程名稱」長度 以及「老師名稱」長度。
要做也不是不行，但第三方服務的資料來源都是透過網頁爬蟲，學校沒有提供 API 或任何資料庫使用方式，真的要透過爬蟲建立一份資料庫也不小的工程，畢竟學校除了日夜校，還有個大系所及班級....
教室位置長度為3-4碼，但可以透過 split 來與前方字串分開取得。

我也遇到一個狀況，班會時間與課堂衝堂的合併顯示。
導師時間王小明 C303電腦課(二)陳先生 W0607
目前暫無解法...

感謝你提出來討論 :)

**Comment by green-leek** [comment]
可是從 html 看起來中間有一個 ```<br>``` 作分隔，應該是可以解決的吧？
```html
<span id="ctl00_ContentPlaceHolder1_dg_dt_ctl02_l_1"><br>導師時間<br>王小明 C303</span>
```

**Comment by MksYi** [comment]
green-leek 你好：
當時是使用 jqeury selector 取得元素並以 ```$(...).text()``` 進行解析
文字就自然的連成一團了...
> 導師時間王小明 C303
> [課程名稱][老師名稱] [教室位置]

看到你提出的觀點
稍早就嘗試以不使用 ```.text()``` 的方式
直接解析 HTML 來取得課表上的欄位資料
也很順利的爬到課程資料~
目前算是解決老師名字不等於3的問題了
程式也變得更簡潔

*但衝堂的問題兩門課程擠在同一個欄位上的問題還是尚未解決（僅會顯示其中一堂課程資料）
這應該就要等以後比較有空再來處理了~

謝謝你的回饋 : )

**Comment by green-leek** [comment]
問題已解決，謝謝。
