### ISSUE TITLE
有夜校的課程卻誤判為沒有

### ISSUE THREAD

**Issue by green-leek** [MksYi/stustExplorer-NodeJS#2]
在 mainPage.jade 裏的 `night >= 24 ? (night = false) : (night = true);` 為什麼需要大於或等於 24 才為 true ? 而數值 24 作用是什麼 ?

**Comment by MksYi** [comment]
green-leek 你好：

後端的程式會將爬取到的課表存成一個二維的變數
{
[ course0, course1, course2 ,course3, ...], //week 1
[ course0, course1, course2 ,course3, ...], //week 2
...
[ course0, course1, course2 ,course3, ...], //week 6
}
其 day、night 代表的數字為空堂數。
當 night > 24 代表夜校尚無課程。
在程式的設定上有做自動 hide()

會誤判的原因應該是從後端就沒有爬到資料了，但目前不知道是哪個環節出了問題，作者都是日校生，只有請幾位夜校同學幫忙測試過，隨後因應選課時間提早上線讓大家使用。

這問題我會多加留意，看有沒有其他人有這樣的問題發生，或多做測試獲取問題加以改進。
謝謝你的回饋 :)

**Comment by green-leek** [comment]
為什麼需要大於或等於 24 才為 true ? 這個 24 是 [魔術數字](https://zh.wikipedia.org/wiki/%E9%AD%94%E8%A1%93%E6%95%B8%E5%AD%97_(%E7%A8%8B%E5%BC%8F%E8%A8%AD%E8%A8%88)) 。

**Comment by green-leek** [comment]
你的代碼中有很多魔術數字又有很多意義不明的注解，令人很難看懂。請務必改一下，謝謝。

**Comment by green-leek** [comment]
我現在遇到的問題是我有修兩門夜間部的課，可是它自動隱藏了。

**Comment by MksYi** [comment]
green-leek 你好：
使用「魔術數字」確實不妥
此外夜校課程自動隱藏是因為計算到不存在的第十節的欄位
所以如果沒有修滿夜校課程超過 6 學分都會自動隱藏
新的版本已經有針對以上問題進行修正
也麻煩請你在試試看問題是否還是存在

謝謝你 : )

**Comment by green-leek** [comment]
問題已解決，謝謝。
